custom:
  app:
    token:
      timeout: 86400
  nosql:
    redis:
      host: 218.17.39.34
      port: 8209
    rabbitmq:
      addresses: 218.17.39.34:8672
      port: 8672
      username: mnet
      password: mnet
  db:
    url: jdbc:mysql://218.17.39.34:3306/testmnet?useUnicode=true&characterEncoding=UTF-8
    username: mnet_business
    password: mnet@123
    driver-class-name: com.mysql.jdbc.Driver
    database-platform: org.hibernate.dialect.MySQL5Dialect
  db1:
    url: jdbc:mysql://218.17.39.34:3306/testmnet?useUnicode=true&characterEncoding=UTF-8
    username: mnet_business
    password: mnet@123
    driver-class-name: com.mysql.jdbc.Driver
    database-platform: org.hibernate.dialect.MySQL5Dialect
  oauth:
    ip: localhost:9710
    clientId: MANAGER
    clientSecret: 123456
  #文件上传配置，保存的路径
  upload:
    #文件保存的路径(服务器主机删的绝对路径，如若没有请新建)
    absolute-path: /home/mnet/montnets/images     
    


eurekaserver:
  ip: localhost
  port: 9709


logging:
  level:
    com.suoju.montnets.common.dao:  DEBUG


token:
  ip: localhost
  expire:
    seconds: 300

swagger:
  enable: true

#调用华为接口相关配置项
remote:
  server:
    appid: 101080723
    baseUrl: http://218.17.39.34:7915
    clientSecret: 24043e04d9a087b7ade2ecaa826f8471
    tokenUrl: http://218.17.39.34:7915/oauth2/v2/token
